name: discover-api
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - flask
  - requests
  - pip
  - flask-cors
  - pip:
      - gunicorn
      - asyncio
      - aiohttp
      - google-cloud-storage
      - google-cloud-bigquery 
      - pandas
      - db-dtypes
      - google-cloud-bigquery-storage